### ISSUE TITLE
Node Integration is not set

### ISSUE THREAD

**Issue by sandipndev** [paul7337/Electron-Get-Folder-Path#1]
After cloning the repo, it didn't work properly for me. It was only when finally I looked around the code, I found out that Node Integration was not set. As of Electron v5+, it is defaulted to false, because of which, it'll show `require is not defined`.

*Suggested Fix* - In function `createWindow`, the first line of the code can just be like
```js
win = new BrowserWindow({width: 800, height: 600, webPreferences: {
    nodeIntegration: true
  }}) 
```

Source: https://stackoverflow.com/a/55908510/11895501

**Comment by paul7337** [comment]
Hi Triethyl, 

Apologies for the delayed response. 

Thanks for the advice!

I'll check out your amend to the code and update the repo if needed.

**Comment by paul7337** [comment]
Hi Triethyl,

Sorry, it took a while to get to this, been super busy. 
I wanted to check whether it would break the solution for older versions. 

I tested with 4.2.2 and it seemed to work ok. Being that Electron is on v7+ now, I think that should be fine, so I've rolled your suggestion in.
